### PR TITLE
Fix/edit concurrent offers

### LINKED ISSUE #121: Update edit offer route to verify for concurrent offers
Apply concurrentOffers middleware to edit route

### PR DESCRIPTION
**Pull request by Naapperas**
Closes #121

### CODE REVIEW

**Comment by Naapperas** [comment]
The fail is caused by introducing the test for `publishEndDate`, which causes an error when testing offer enabling.

File: src/api/middleware/validators/validatorUtils.js [hunk 1]
```diff
@@ -61,12 +61,13 @@ const sortOffersByFieldAscending = (field) => (offer1, offer2) => Date.parse(off
...
  * @param {*} publishEndDate Date in which the offer will end
+ * @param {*} offerId the id of the offer to exclude from the count, if defined
  */
-const concurrentOffersNotExceeded = (OfferModel) => async (owner, publishDate, publishEndDate) => {
+const concurrentOffersNotExceeded = (OfferModel) => async (owner, publishDate, publishEndDate, offerId) => {
     // We need to pass the offer model in case we're inside an Offer instance
     const offersInTimePeriod = await (new CompanyService())
         .getOffersInTimePeriod(owner, publishDate, publishEndDate, OfferModel)
-        .withoutHidden();
+        .withoutHidden().find(offerId ? { _id: { $ne: offerId } } : {});
```
Comment (limwa) [inline src/api/middleware/validators/validatorUtils.js:70]:
```suggestion
        .withoutHidden().where(offerId ? { _id: { $ne: offerId } } : {});
```

**Review by limwa — COMMENTED** [review]
I think this might be a fix for the CI problems

**Comment by Naapperas** [comment]
I think that this changes should be added after #151 is dealt with.

**Comment by imnotteixeira** [comment]
> I think that this changes should be added after #151 is dealt with.

Also #144 might be helpful as well, since that logic is being used here

File: src/api/middleware/company.js [hunk 2]
```diff
@@ -22,6 +24,32 @@ const verifyMaxConcurrentOffers = (owner, publishDate, publishEndDate) => async
     return next();
 };
 
+const verifyMaxConcurrentOffersOnCreate = (req, res, next) => {
+
+    if (req.body?.isHidden) return next();
+
+    const owner = req.user?.company || req.body.owner;
```
Comment (imnotteixeira) [inline src/api/middleware/company.js:31]: Maybe wait for #144 to avoid this

File: src/api/middleware/company.js [hunk 3]
```diff
@@ -22,6 +24,32 @@ const verifyMaxConcurrentOffers = (owner, publishDate, publishEndDate) => async
...
+
+    return verifyMaxConcurrentOffers(owner, publishDate, publishEndDate)(req, res, next);
+
+};
+
+const verifyMaxConcurrentOffersOnEdit = async (req, res, next) => {
+
+    if (req.body?.isHidden) return next();
+
+    const offer = await Offer.findById(req.params.offerId);
```
Comment (imnotteixeira) [inline src/api/middleware/company.js:43]: Wrap this in a try catch, since the call to the db can fail. Additionally, you should use the service and not direct db calls
```suggestion
    try {
                const offer = await (new OfferService()).getOfferById(req.params.offerId, req.user);
                if (!offer) throw new APIError(HTTPStatus.NOT_FOUND, ErrorTypes.VALIDATION_ERROR, ValidationReasons.OFFER_NOT_FOUND(req.params.offerId));
            } catch (err) {
                console.error(err);
                return next(err);
            }
```

Comment (imnotteixeira) [reply src/api/middleware/company.js:43]: By doing this, you can avoid the ?. operators later, since inside the try block, the offer always exists.

File: src/api/middleware/validators/offer.js [hunk 4]
```diff
@@ -508,13 +508,14 @@ const canBeManaged = async (req, res, next) => {
...
     if ((!req.user?.isAdmin && req.body.god_token !== config.god_token) &&
-         offer.hiddenReason === OfferConstants.HiddenOfferReasons.ADMIN_BLOCK) {
+        offer.hiddenReason === OfferConstants.HiddenOfferReasons.ADMIN_BLOCK) {
         return next(new APIError(HTTPStatus.FORBIDDEN, ErrorTypes.FORBIDDEN, ValidationReasons.OFFER_BLOCKED_ADMIN));
     }
 
     return next();
 };
 
+// Validator to check if the offer can be enabled
```
Comment (imnotteixeira) [inline src/api/middleware/validators/offer.js:518]: Why this comment? I think the function name is pretty self-explanatory

File: src/api/middleware/validators/validatorUtils.js (hunk 1 above)
Comment (imnotteixeira) [inline src/api/middleware/validators/validatorUtils.js:70]:
```suggestion
        .withoutHidden()
        .find(offerId ? { _id: { $ne: offerId } } : {});
```

**Review by imnotteixeira — CHANGES_REQUESTED** [review]

File: src/api/middleware/validators/offer.js (hunk 4 above)
Comment (Naapperas) [reply src/api/middleware/validators/offer.js:518]: The rest of the functions had a describing comment to go with them, so i thought it would be better to also add it here

File: src/api/middleware/company.js [hunk 5]
```diff
@@ -40,13 +41,25 @@ const verifyMaxConcurrentOffersOnEdit = async (req, res, next) => {
...
+        const publishDate =  req.body.publishDate || offer.publishDate;
+        const publishEndDate = req.body.publishEndDate || offer.publishEndDate;
+
+        return verifyMaxConcurrentOffers(owner, publishDate, publishEndDate, offer._id)(req, res, next);
+
+    } catch (err) {
+
+        console.error(err);
+
+        return next(err);
```
Comment (imnotteixeira) [inline src/api/middleware/company.js:61]:
```suggestion
        console.error(err);
        return next(err);
```

**Review by imnotteixeira — CHANGES_REQUESTED** [review]

File: src/api/middleware/validators/offer.js (hunk 4 above)
Comment (imnotteixeira) [reply src/api/middleware/validators/offer.js:523]: Remove the comment. It adds nothing to the function name

**Review by imnotteixeira — CHANGES_REQUESTED** [review]

**Review by imnotteixeira — APPROVED** [review]
