### PR TITLE
Fix/publish time limit

### LINKED ISSUE #98: Add validation for offer publishEndDate not after x time from publishStartDate
A company cannot have an offer published more than 6 months (currently)

This validation is only done in the Model level. When it fails, the error is thrown but it is an UnknownError since they are masked before outputting. We should have a validator on the route level so that it throws a comprehensive error

### PR DESCRIPTION
**Pull request by henriquecscode**
Closes #98 

Added validators to the publishEndDate of a offer to both the create and edit operations. The publishEndDate must not exceeda time limit that is defined in the TimeConstants

### CODE REVIEW

File: src/api/middleware/validators/offer.js [hunk 1]
```diff
@@ -11,13 +11,44 @@ const OfferConstants = require("../../../models/constants/Offer");
...
 const HTTPStatus = require("http-status-codes");
 const {
     HOUR_IN_MS,
     OFFER_EDIT_GRACE_PERIOD_HOURS,
+    MONTH_IN_MS,
+    OFFER_MAX_LIFETIME_MONTHS
 } = require("../../../models/constants/TimeConstants");
 
+
+const publishEndDateBeforePublishDate = (publishEndDateCandidate, { req }) => {
```
Comment (imnotteixeira) [inline src/api/middleware/validators/offer.js:25]: Change the name to `publishEndDateAfterPublishDate`, since that's what is really being enforced

File: src/api/middleware/validators/offer.js [hunk 2]
```diff
@@ -11,13 +11,44 @@ const OfferConstants = require("../../../models/constants/Offer");
...
+    if (publishEndDateCandidate <= publishDate) {
+        // end date is earlier than publish date, error!
+        throw new Error(ValidationReasons.MUST_BE_AFTER("publishDate"));
+    }
+
+    // Returning truthy value to indicate no error ocurred
+    return true;
+};
+
+const PublishEndDateLimit = (publishEndDateCandidate, { req }) => {
```
Comment (imnotteixeira) [inline src/api/middleware/validators/offer.js:39]: use camelcase
```suggestion
const publishEndDateLimit = (publishEndDateCandidate, { req }) => {
```

File: src/api/middleware/validators/offer.js [hunk 3]
```diff
@@ -262,7 +282,9 @@ const edit = useExpressValidators([
         .optional()
         .isISO8601({ strict: true }).withMessage(ValidationReasons.DATE).bail()
         .isAfter().withMessage(ValidationReasons.DATE_EXPIRED).bail()
-        .custom(publishEndDateEditable),
+        .custom(publishEndDateEditable)
+        .custom(publishEndDateBeforePublishDate)
```
Comment (imnotteixeira) [inline src/api/middleware/validators/offer.js:286]: This is unnecessary since publishEndDateEditable already does the check (and more - since it checks the current value of publishDate in the offer, for example)

File: src/models/Offer.js [hunk 4]
```diff
@@ -107,8 +107,13 @@ function validatePublishDate(value) {
 }
 
 function validateEndDate(value) {
+    return validatePublishEndDateLimit(this.publishDate, value);
+}
+
+function validatePublishEndDateLimit(publishDate, endDate) {
```
Comment (imnotteixeira) [inline src/models/Offer.js:113]:
```suggestion
function validatePublishEndDateLimit(publishDate, publishEndDate) {
```

File: test.sh [hunk 5]
```diff
@@ -1,3 +1,3 @@
-#!/usr/bin/env sh
-
-PORT=3001 docker-compose up --exit-code-from test "$1" test
+#!/usr/bin/env sh
+
+PORT=3001 docker-compose up --exit-code-from test "$1" test
```
Comment (imnotteixeira) [inline test.sh:3]: I think this file slipped in the CRLF/LF problem. Unstage it since it does not belong in this PR

File: test/end-to-end/offer.js [hunk 6]
```diff
@@ -286,6 +291,41 @@ describe("Offer endpoint tests", () => {
                 await Offer.deleteMany({});
             });
 
+            beforeEach(async () => {
+                await Offer.deleteMany({});
+            });
+
+            test("Should fail to create an offer due to publish end date being six months after publish date", async () => {
```
Comment (imnotteixeira) [inline test/end-to-end/offer.js:298]: The title should be generic so that if we change the limit, we don't have to change the test. Instead of "six months", change to "being after publish date more than the limit"

File: test/end-to-end/offer.js [hunk 7]
```diff
@@ -286,6 +291,41 @@ describe("Offer endpoint tests", () => {
...
+                };
+
+                const res = await request()
+                    .post("/offers/new")
+                    .send(withGodToken(offer_params));
+
+                expect(res.status).toBe(HTTPStatus.UNPROCESSABLE_ENTITY);
+                const error = res.body;
+
+                console.info("test1234", error);
```
Comment (imnotteixeira) [inline test/end-to-end/offer.js:316]: Remove

**Review by imnotteixeira — CHANGES_REQUESTED** [review]

**Review by imnotteixeira — CHANGES_REQUESTED** [review]

File: src/api/middleware/validators/offer.js [hunk 8]
```diff
@@ -262,7 +282,8 @@ const edit = useExpressValidators([
         .optional()
         .isISO8601({ strict: true }).withMessage(ValidationReasons.DATE).bail()
         .isAfter().withMessage(ValidationReasons.DATE_EXPIRED).bail()
-        .custom(publishEndDateEditable),
+        .custom(publishEndDateEditable)
+        .custom(publishEndDateLimit),
```
[the remark this answers is not in the document]
Comment (imnotteixeira) [reply src/api/middleware/validators/offer.js:286]: Also, add a test for this case in the offer edit tests section, to make sure this works as intended

File: test/end-to-end/offer.js [hunk 9]
```diff
@@ -286,6 +291,35 @@ describe("Offer endpoint tests", () => {
...
+                    owner: test_company._id,
+                    ownerName: test_company.name,
+                    publishDate: publishDate.toISOString(),
+                    publishEndDate: (new Date(publishDate.getTime() + (MONTH_IN_MS * OFFER_MAX_LIFETIME_MONTHS) + DAY_TO_MS)).toISOString(),
+                };
+
+                const res = await request()
+                    .post("/offers/new")
+                    .send(withGodToken(offer_params));
+
```
Comment (imnotteixeira) [inline test/end-to-end/offer.js:312]: I meant to only remove the console.info, I don't know why the comment had multiple lines.

Add the status check as it were
`expect(res.status).toBe(HTTPStatus.UNPROCESSABLE_ENTITY);`

File: test/end-to-end/offer.js [hunk 10]
```diff
@@ -286,6 +291,35 @@ describe("Offer endpoint tests", () => {
                 await Offer.deleteMany({});
             });
 
+            beforeEach(async () => {
+                await Offer.deleteMany({});
+            });
+
+            test("Should fail to create an offer due to publish end date being aftr publish date more than the limit", async () => {
```
Comment (imnotteixeira) [inline test/end-to-end/offer.js:298]: fix "after" typo

File: test/end-to-end/offer.js [hunk 11]
```diff
@@ -1383,14 +1417,35 @@ describe("Offer endpoint tests", () => {
...
-                                .toISOString()
+                                (new Date(new Date(future_test_offer.publishDate).getTime() - DAY_TO_MS))
+                                    .toISOString()
                         }))
                         .expect(HTTPStatus.UNPROCESSABLE_ENTITY);
                     expect(res.body.errors[0]).toHaveProperty("param", "publishEndDate");
                     expect(res.body.errors[0]).toHaveProperty("msg", ValidationReasons.MUST_BE_AFTER("publishDate"));
                 });
 
+                test("should fail if publishEndDate is after publishDate more than the time limit", async () => {
```
Comment (imnotteixeira) [inline test/end-to-end/offer.js:1428]:
```suggestion
                test("should fail to edit if publishEndDate is after publishDate more than the time limit", async () => {
```

**Review by imnotteixeira — CHANGES_REQUESTED** [review]

**Review by imnotteixeira — COMMENTED** [review]
This should be good to go. As talked offline, will defer approval until the commits are "cleaned up"

**Review by imnotteixeira — APPROVED** [review]
