### PR TITLE
Fixed mentioned hardcoded constants + some others

### LINKED ISSUE #197: Fix hardcoded constants
There are some hardcoded constants that should be replaced by their variable versions, to make the code cleaner and more modular. I found these, but there may be more.

https://github.com/NIAEFEUP/nijobs-be/blob/develop/src/api/middleware/validators/auth.js#L19

https://github.com/NIAEFEUP/nijobs-be/blob/develop/src/api/middleware/validators/offer.js#L336

### PR DESCRIPTION
**Pull request by pedrosilva17**
Closes #197

### CODE REVIEW

File: src/api/middleware/validators/company.js [hunk 1]
```diff
@@ -30,7 +30,7 @@ export const list = useExpressValidators([
     query("offset", ValidationReasons.DEFAULT)
         .optional()
         .isInt({ min: 0 })
-        .withMessage(ValidationReasons.MIN(0)),
+        .withMessage(ValidationReasons.MIN(ValidationReasons.MIN)),
```
Comment (DoStini) [inline src/api/middleware/validators/company.js:33]: This doesn't seem right

File: src/api/middleware/validators/offer.js [hunk 2]
```diff
@@ -116,7 +116,7 @@ export const create = useExpressValidators([
     body("contacts", ValidationReasons.DEFAULT)
         .exists().withMessage(ValidationReasons.REQUIRED).bail()
         .isArray({ min: 1 })
```
Comment (DoStini) [inline src/api/middleware/validators/offer.js:118]: Replace with constant

File: src/api/middleware/validators/company.js (hunk 1 above)
Comment (DoStini) [reply src/api/middleware/validators/company.js:33]: I think 0 is fine in this situation, because it's an offset of a query

File: src/api/middleware/validators/offer.js [hunk 3]
```diff
@@ -183,7 +183,7 @@ export const create = useExpressValidators([
     body("requirements", ValidationReasons.DEFAULT)
         .exists().withMessage(ValidationReasons.REQUIRED).bail()
         .isArray({ min: 1 })
```
Comment (DoStini) [inline src/api/middleware/validators/offer.js:185]: Replace with constant

File: src/api/middleware/validators/offer.js [hunk 4]
```diff
@@ -333,7 +333,7 @@ export const edit = useExpressValidators([
     body("title", ValidationReasons.DEFAULT)
         .optional()
         .isString().withMessage(ValidationReasons.STRING)
-        .isLength({ max: OfferConstants.title.max_length }).withMessage(ValidationReasons.TOO_LONG(90))
+        .isLength({ max: OfferConstants.title.max_length }).withMessage(ValidationReasons.TOO_LONG(OfferConstants.title.max_length))
         .trim(),
```
Comment (DoStini) [inline src/api/middleware/validators/offer.js:337]: I just noticed there's a missing validator here and in create. You need to add a min parameter to the offer title, let's set it to 1 for now. If we try to create an offer with an empty title, we will get an unexpected error.
What you gotta do is:

- Add an isLenght with `ValidationReasons.TOO_SHORT` and with `min: OfferConstants.title.min_length` validator in [here](https://github.com/NIAEFEUP/nijobs-be/blob/b3570e2561799f89543f04e5195a04b1eb7d9735/src/api/middleware/validators/offer.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L77) and [here](https://github.com/NIAEFEUP/nijobs-be/blob/b3570e2561799f89543f04e5195a04b1eb7d9735/src/api/middleware/validators/offer.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L336)
- Create an entry in offer constants
- Create a test that verifies this behavour

File: src/api/middleware/validators/offer.js [hunk 5]
```diff
@@ -376,7 +376,7 @@ export const edit = useExpressValidators([
     body("contacts", ValidationReasons.DEFAULT)
         .optional()
         .isArray({ min: 1 })
```
Comment (DoStini) [inline src/api/middleware/validators/offer.js:378]: Replace with constant

File: src/api/middleware/validators/offer.js [hunk 6]
```diff
@@ -416,7 +416,7 @@ export const edit = useExpressValidators([
     body("requirements", ValidationReasons.DEFAULT)
         .optional()
         .isArray({ min: 1 })
```
Comment (DoStini) [inline src/api/middleware/validators/offer.js:418]: Replace with constant

**Review by DoStini — CHANGES_REQUESTED** [review]

File: src/api/middleware/validators/company.js (hunk 1 above)
Comment (pedrosilva17) [reply src/api/middleware/validators/company.js:33]: Yeah this one doesn't make sense, I was testing in the beginning and forgot to change this one back. Will make the rest of the adjustments today

**Comment by DoStini** [comment]
- Since you added a validator for min lenght, do the same for the database model, [here](https://github.com/NIAEFEUP/nijobs-be/blob/340582948f4af5c8b182703f54fadc2ef9bb3711/src/models/Offer.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L15).
- Your branch is out of date so you need to rebase: go to develop, pull, go back to your branch and run `git rebase develop`, if there are conflicts, this might get tricky, ask for help if you need it
- `npm audit fix` to solve the audit problem

**Review by DoStini — CHANGES_REQUESTED** [review]
Add a validator to the database model

**Comment by pedrosilva17** [comment]
Weird, I ran `npm audit fix` and the check is still failing (with 0 vulnerabilities, apparently). I think the rebase was done successfully.

**Comment by DoStini** [comment]
You didn't commit package lock files, that's probably why

**Comment by pedrosilva17** [comment]
Completely forgot. Will do that in a second

**Comment by DoStini** [comment]
When you make a rebase you should `git push --force-with-lease` instead of a normal `git push`.

**Review by DoStini — APPROVED** [review]
