### PR TITLE
Fix/date validators

### LINKED ISSUE #50: Fix validation (Dates)
When passing a past end date, and no publish date, it takes the default publish date which is `now`, however, since end date is in the past, it crashes without failing the validation. It should check the endDate vs publishDate on validation.

Another approach would be to prevent the creation of offers with an end date in the past.

Just to clarify, the model has a jobStartDate, and jobDuration, that refer to the job itself, however publish date and end date refer to the job posting, maybe we should change the endDate naming to make it clearer (maybe publishEndDate?)

### PR DESCRIPTION
**Pull request by miguelpduarte**
Closes #50

### CODE REVIEW

**Comment by miguelpduarte** [comment]
@imnotteixeira As mentioned in person (and just verified) the data is correctly inserted when the `publishEndDate` is larger that `publishDate` and they are both in the future. However (also like predicted) when they are swapped (but still both in the future) there is a mongoose validation error thrown in the server and an empty 500 response is returned.

Adding validation for this now.

**Comment by miguelpduarte** [comment]
@imnotteixeira Should be good to go now. Re-requesting review. Sorry for the delay, it was caused by the surgery recovery mostly :sweat_smile:

**Comment by imnotteixeira** [comment]
@miguelpduarte Didn't know there was spaghetti code fixing surgery 😈😈

File: src/api/middleware/validators/offer.js [hunk 1]
```diff
@@ -17,13 +17,28 @@ const create = useExpressValidators([
...
+                || (new Date(Date.now())).toISOString();
+
+            if (value <= checkPublishDate) {
+                // end date is earlier than publish date, error!
+                throw new Error(ValidationReasons.MUST_BE_AFTER("publishDate"));
+            }
+
+            // Returning truthy value to indicate no error ocurred
+            return true;
+        })
```
Comment (imnotteixeira) [inline src/api/middleware/validators/offer.js]: Looks good! However, I would suggest some var names renaming:

* `value `-> `publishEndDateCandidate`
* `publishDate` -> `publishDateRaw`
* `checkPublishDate` -> `publishDate`

In this case the if would be way clearer: `if (publishEndDate <= publishDate)`

File: test/end-to-end/offer.js [hunk 2]
```diff
@@ -150,7 +151,7 @@ describe("Offer endpoint tests", () => {
             test("Should successfully create an Offer", async () => {
                 const offer = {
                     title: "Test Offer",
-                    publishDate: "2019-11-17T00:00:00.000Z",
+                    publishDate: new Date(Date.now() - (24 * 3600 * 1000)),
```
Comment (imnotteixeira) [inline test/end-to-end/offer.js]: That magic constant is being used twice here and in other files as well, can you create a global `const DAY_TO_MS` with that value?

File: test/utils/ValidatorTester.js [hunk 3]
```diff
@@ -82,6 +82,27 @@ const ValidatorTester = (requestEndpoint) => (location) => (field_name) => ({
         });
     },
 
+    mustBeAfter: (field_name2) => {
+        test(`should be after ${field_name2}`, async () => {
+            const params = {
+                [field_name]: new Date(Date.now()).toISOString(),
+                [field_name2]: new Date(Date.now() + (24 * 3600 * 1000)).toISOString(),
```
Comment (imnotteixeira) [inline test/utils/ValidatorTester.js]: `DAY_TO_MS` usage

File: src/api/middleware/validators/offer.js (hunk 1 above)
Comment (miguelpduarte) [reply src/api/middleware/validators/offer.js]: Done. Though of other options but these ended up being the ones I agreed the most with.

File: test/end-to-end/offer.js (hunk 2 above)
Comment (miguelpduarte) [reply test/end-to-end/offer.js]: done

File: test/utils/ValidatorTester.js (hunk 3 above)
Comment (miguelpduarte) [reply test/utils/ValidatorTester.js]: also done ^^

File: test/utils/ValidatorTester.js [hunk 4]
```diff
@@ -63,6 +64,46 @@ const ValidatorTester = (requestEndpoint) => (location) => (field_name) => ({
...
     },
 
+    mustBeFuture: () => {
+        test("should be a future Date", async () => {
+            const params = {
+                [field_name]: "1998-12-25",
+            };
+            const res = await requestEndpoint(params);
+
+            expect(res.status).toBe(422);
```
Comment (GuilhermeJSilva) [inline test/utils/ValidatorTester.js]: Update to use the enum `HTTPStatus` from `http-status-codes`

File: test/utils/ValidatorTester.js [hunk 5]
```diff
@@ -63,6 +64,46 @@ const ValidatorTester = (requestEndpoint) => (location) => (field_name) => ({
...
+    mustBeAfter: (field_name2) => {
+        test(`should be after ${field_name2}`, async () => {
+            const params = {
+                [field_name]: new Date(Date.now()).toISOString(),
+                [field_name2]: new Date(Date.now() + (DAY_TO_MS)).toISOString(),
+            };
+
+            const res = await requestEndpoint(params);
+
+            expect(res.status).toBe(422);
```
Comment (GuilhermeJSilva) [inline test/utils/ValidatorTester.js]: Same as comment above

File: test/utils/ValidatorTester.js (hunk 4 above)
Comment (miguelpduarte) [reply test/utils/ValidatorTester.js]: A rebase was necessary, as this was actually done in #63. However, took the chance and extracted some of the common assertions in `ValidatorTester.js` to a separate function, which makes the code cleaner imo :slightly_smiling_face:

Comment (miguelpduarte) [reply test/utils/ValidatorTester.js]: Please check it out now

File: test/utils/ValidatorTester.js [hunk 6]
```diff
@@ -1,8 +1,19 @@
...
+
 const { ErrorTypes } = require("../../src/api/middleware/errorHandler");
 const ValidationReasons = require("../../src/api/middleware/validators/validationReasons");
 const { DAY_TO_MS } = require("../utils/TimeConstants");
 
+/**
+ * Checks the common parts of the error response: the status code, error_code property and that the body also has the error properties
+ * @param {*} res The response object
+ */
+const checkCommonErrorResponse = (res) => {
```
Comment (imnotteixeira) [inline test/utils/ValidatorTester.js]: Shouldn't this be `checkValidationErrorResponse`? The first thought I had when reading was that this would check for 500 errors, as they are the common/generic. Since this checks for 422 (specific request validation error), the function name should be clearer

Comment (miguelpduarte) [reply test/utils/ValidatorTester.js]: As the doc comment mentions, this "Checks the common parts of the error response". This method was created to reduce the code duplication since there were some parts that were repeated along this file.

Since this does not check the full response, and only the parts that are common in the response between all of the validator tests, this name was chosen. As such, I see no issue with it, and think that `checkValidationErrorResponse` would be misleading as it would seem like it would check for all of the response, but only performs checks on a small part of it, since the separate tests below perform the remaining checks.

Comment (miguelpduarte) [reply test/utils/ValidatorTester.js]: Furthermore, since this function is only used in this file, has a doc comment that explains it, and is not even exported from the file, I think this is pointless bikeshedding :sweat_smile:

Comment (miguelpduarte) [reply test/utils/ValidatorTester.js]: I guess it could be renamed to `checkCommonValidationErrorResponse` but that is just a mouthful, and sincerely irrelevant given the reasons above.

Comment (imnotteixeira) [reply test/utils/ValidatorTester.js]: Sure, since this is a single-file thing (not exported), used to reduce repetition and the file is the validation one, the renaming is not as important, let's ship this
