### PR TITLE
Fix bug that only allowed companies to register with multiple contacts

### LINKED ISSUE #137: [Bug] Ensure that companies can complete registration with only one contact
Currently, if we make a request with a single contact, it will be parsed as a string, instead of an array, giving an error:

image

> The [ ] are not actually needed, I was just trying to debug it

This happens (I suspect) because the validator is not using the `ensureArray` utility we've created for these types of scenarios, like the filtering in offer search, for example, or the state filtering of company applications.

It should only be a matter of adding it to the validator before the `isArray` check

Also, add a test where a single contact is posted, to validate this behavior

### PR DESCRIPTION
**Pull request by GuilhermeJSilva**
Closes #137

### CODE REVIEW

File: test/end-to-end/company.js [hunk 1]
```diff
@@ -100,6 +100,32 @@ describe("Company application endpoint", () => {
...
 
+            test("should finish the application with single contact", async () => {
+                await test_agent
+                    .post("/company/application/finish")
+                    .attach("logo", "test/data/logo-niaefeup.png")
+                    .field("bio", "A very interesting and compelling bio")
+                    .field("contacts", "contact1")
+                    .expect(HTTPStatus.OK);
+
+                const test_company = [... await Company.find({}).exec()][0];
```
Comment (imnotteixeira) [inline test/end-to-end/company.js:111]: No need for `.exec()`

```suggestion
                const test_company = [... await Company.find({})][0];
```

Comment (imnotteixeira) [inline test/end-to-end/company.js:111]: define test_company on the describe level (outside of the beforeEach) and here you won't need to query the db, making the test faster, as you can access test_company directly.

You should do this (also remove the .exec) on the test above

**Review by imnotteixeira — CHANGES_REQUESTED** [review]

File: test/end-to-end/company.js (hunk 1 above)
Comment (GuilhermeJSilva) [reply test/end-to-end/company.js:111]: The company is updated in each test (contacts are added, etc), therefore a new db query is necessary

File: test/end-to-end/company.js [hunk 2]
```diff
@@ -100,6 +100,32 @@ describe("Company application endpoint", () => {
...
+                expect(test_company.bio).toBe("A very interesting and compelling bio");
+                const filename = path.join(__dirname, `../../${test_company.logo}`);
+                expect(fs.existsSync(filename)).toBe(true);
+
+                await test_agent
+                    .post("/company/application/finish")
+                    .attach("logo", "test/data/logo-niaefeup.png")
+                    .field("bio", "A very interesting and compelling bio")
+                    .field("contacts", ["contact1", "contact2"])
+                    .expect(HTTPStatus.FORBIDDEN);
```
Comment (imnotteixeira) [inline test/end-to-end/company.js:123]: Please validate the error message (and in the previous test, I hadn't noticed), please. Other than that, it can be merged

**Review by imnotteixeira — CHANGES_REQUESTED** [review]

**Review by imnotteixeira — CHANGES_REQUESTED** [review]
Rebase from develop and unstage package-lock, that will probably make the tests pass
