### PR TITLE
Fix/hide admin reason

### LINKED ISSUE #149: Do not return `adminReason` to non-admin/god on offer GET
This is an internal-only field, so it should not be returned if the entity fetching the offer is a visitor or a logged in company.

### PR DESCRIPTION
**Pull request by Naapperas**
Closes #149

### CODE REVIEW

**Comment by DoStini** [comment]
Now that I see this, when does this happen? When an offer is hidden it isn't shown to the unprivileged user, and the adminReason only exists when an offer is disabled (hidden)

**Comment by Naapperas** [comment]
> Now that I see this, when does this happen? When an offer is hidden it isn't shown to the unprivileged user, and the adminReason only exists when an offer is disabled (hidden)

Currently when a company is logged in they can see their offers, hidden or not, using the `GET /offers/:offerId` route. However, if said offer was disabled, they should not be able to see the reason given to disable it, since it is an internal field, hence this PR. 

The logic for that was also extended for the more general `GET /offers`, even though hidden offers don't appear to non-admin/god users.

**Comment by DoStini** [comment]
Oh yeah, that makes sense

File: src/services/offer.js [hunk 1]
```diff
@@ -225,10 +227,15 @@ class OfferService {
...
+    async getOfferById(offerId, user, showAdminReason = false) {
+        const offerQuery = Offer.findById(offerId);
+
+        if (!showAdminReason) offerQuery.select("-adminReason");
+
+        const offer = await offerQuery;
 
-        if (offer?.isHidden && !(user?.isAdmin || offer.owner.toString() === user?.company?._id.toString())) return null;
+        // this is a good fix for now but should be changed later
+        if (offer?.isHidden && !(user?.isAdmin || showAdminReason || offer.owner.toString() === user?.company?._id.toString())) return null;
```
Comment (imnotteixeira) [inline src/services/offer.js:238]: Why is the `showAdminReason` relevant in this line?

**Review by imnotteixeira — CHANGES_REQUESTED** [review]

File: src/api/middleware/utils.js [hunk 2]
```diff
@@ -81,9 +82,19 @@ const when = (
...
 
+/**
+ * Checks if a god token was sent in the request, indicating that the user might be in god mode.
+ */
+const godMode = (req, _, next) => {
+    if (req.body?.god_token === config.god_token) req.godMode = true;
+
+    return next();
+};
+
```
[the remark this answers is not in the document]
Comment (Naapperas) [reply src/api/middleware/utils.js:93]: So, if I understood correctly, this logic should be inside `src/middleware/auth.js`, right? 
Also, should I change every `isAdmin, isGod` that might be inside a call to the `or` util to `hasAdminPermissions`, since those are already going to be covered by it ?

[the remark this answers is not in the document]
Comment (imnotteixeira) [reply src/api/middleware/utils.js:93]: Yes, sorry I had the wrong link for the code.

No don't change the validation, these are different things. In this case you won't validate anything, you'll simply provide a utility variable for future code to depend on it. It can be useful for scenarios where you can be a company account with permissions vs. an admin/god and we need to change behavior based on which of these the user is.

Besides, changing the validators to use the hasAdminPermissions defeats the purpose of the creation of the `or` util, which was built to give more context to the reader about what validation is doing, and modularity.

File: src/api/routes/offer.js [hunk 3]
```diff
@@ -19,12 +19,13 @@ module.exports = (app) => {
      * Gets all currently active offers (without filtering, for now)
      * supports offset and limit as query params
      */
-    router.get("/", validators.get, async (req, res, next) => {
+    router.get("/", godMode, validators.get, async (req, res, next) => {
```
[the remark this answers is not in the document]
Comment (Naapperas) [reply src/api/routes/offer.js:22]: Since the auth router is the first one to be loaded (at least it looks like it), is it ok to just put the `app.use` call in the `auth` route?

[the remark this answers is not in the document]
Comment (imnotteixeira) [reply src/api/routes/offer.js:22]: That could work, but I think it's probably safer to have another file for stuff like this. #144 will require a similar thing and you could "set the pattern" and create a file requestEnhancers.js and you load them on loaders/express.js, just before the routes are loaded

File: src/services/offer.js (hunk 1 above)
Comment (Naapperas) [reply src/services/offer.js:238]: If  `user?.isAdmin` was replaced with `showAdminReason`, some tests would fail because not all calls to `getOfferById` have a third parameter, thus, even though the user could be an admin, that information would never be used inside this method.
I can't think of a good solution off the top of my head, so any suggestions are welcome.

Comment (imnotteixeira) [reply src/services/offer.js:238]: What I meant was that `showAdminReason` has nothing to do with this line. It simply controls if the offer is to be returned or not, which should be refactored to use `req.hasAdminPermissions` instead of `user?.isAdmin`.

`showAdminReason` simply alters the query above, that's fine

Comment (Naapperas) [reply src/services/offer.js:238]: Oh ok, got it

File: src/services/offer.js [hunk 4]
```diff
@@ -227,15 +227,15 @@ class OfferService {
         return constraints.length ? { "$and": constraints } : {};
     }
 
-    async getOfferById(offerId, user, showAdminReason = false) {
+    async getOfferById(offerId, req, showAdminReason = false) {
```
Comment (imnotteixeira) [inline src/services/offer.js:230]: The function should not receive the entire request object, but only the boolean `req.hasAdminPrivileges`. You can call the arg `hasAdminPrivileges` to make it easy to understand.

This is based on the premise that service functions shouldn't need to know about requests or routing or whatever, we could easily call them aside from that (which makes it easier for testing for example)

**Review by imnotteixeira — CHANGES_REQUESTED** [review]

File: src/loaders/requestEnhancers.js [hunk 5]
```diff
@@ -0,0 +1,8 @@
+const { hasAdminPrivileges } = require("../api/middleware/auth");
+
+module.exports = (app) => {
+
+    // check if user is god or admin
```
Comment (imnotteixeira) [inline src/loaders/requestEnhancers.js:5]:
```suggestion
    // Populates req.hasAdminPrivileges accordingly
```

File: src/services/offer.js [hunk 6]
```diff
@@ -225,10 +227,15 @@ class OfferService {
...
-        const offer = await Offer.findById(offerId);
+    async getOfferById(offerId, user, hasAdminPrivileges, showAdminReason = false) {
+        const offerQuery = Offer.findById(offerId);
+
+        if (!showAdminReason) offerQuery.select("-adminReason");
+
+        const offer = await offerQuery;
 
-        if (offer?.isHidden && !(user?.isAdmin || offer.owner.toString() === user?.company?._id.toString())) return null;
+        // this is a good fix for now but should be changed later
```
Comment (imnotteixeira) [inline src/services/offer.js:237]:
```suggestion

```

File: test/unit/auth.js [hunk 7]
```diff
@@ -0,0 +1,75 @@
...
+        });
+
+        test("req body should have hasAdminPrivileges set to 'false' if non-admin/god user is sent", async () => {
+
+            const reqBody = {};
+
+            const req = {
+                body: reqBody,
+                user: test_user
+            };
```
Comment (imnotteixeira) [inline test/unit/auth.js:53]:
```suggestion
            const req = {
                body: {},
                user: test_user
            };
```

File: test/unit/auth.js [hunk 8]
```diff
@@ -0,0 +1,75 @@
...
+        });
+
+        test("req body should have hasAdminPrivileges set to 'false' if no user is sent", async () => {
+
+            const reqBody = {};
+
+            const req = {
+                body: reqBody
+            };
+
```
Comment (imnotteixeira) [inline test/unit/auth.js:68]:
```suggestion
            const req = {
                body: {},
            };
```

File: test/unit/auth.js [hunk 9]
```diff
@@ -0,0 +1,75 @@
...
+        });
+
+        test("req body should have hasAdminPrivileges set to 'true' if admin user is sent", async () => {
+
+            const reqBody = {};
+
+            const req = {
+                body: reqBody,
+                user: test_user_admin
+            };
```
Comment (imnotteixeira) [inline test/unit/auth.js:38]:
```suggestion
            const req = {
                body: {},
                user: test_user_admin
            };
```

File: test/unit/auth.js [hunk 10]
```diff
@@ -0,0 +1,75 @@
...
+        const test_user = {
+            email: "user@email.com",
+            password: "password123",
+        };
+
+        test("req body should have hasAdminPrivileges set to 'true' if god_token is sent", async () => {
+
+            const reqBody = withGodToken();
+
+            const req = { body: reqBody };
```
Comment (imnotteixeira) [inline test/unit/auth.js:23]:
```suggestion
            const req = { body: withGodToken() };
```

**Review by imnotteixeira — CHANGES_REQUESTED** [review]
After applying these changes, rebase from updated master to clear conflicts and allow merge

**Review by imnotteixeira — APPROVED** [review]
